name: CI

on:
  push:
    paths-ignore:
      - README.md

jobs:
  build-docker-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Setup Go
        id: setup-go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_WRITE_TOKEN }}

      - name: Build and Push
        uses: docker/bake-action@v5
        with:
          files: docker-bake.hcl
          push: true
        env:
          TAGS: latest
          REGISTRY: docker.io/mapped